var skill_list  = {Fireball: { usage: "attack",
                               type: "inte",
                               cost: 7,
                               base: 0, 
                               multi: 1.3,
                               base_cd: 2,
                   },
                   Explosion:{ usage: "attack",
                               type: "inte",
                               cost: 15,
                               base: 1, 
                               multi: 1.5,
                               base_cd: 3,
                              
                   },
                   Alacrity:{ usage: "buff",
                               type: "dex",
                               cost: 4,
                               base: 0, 
                               multi: 50,
                               base_cd: 4,
                              
                   },
                   Deadly_shot:{ usage: "attack",
                                 type: "dex",
                                 cost: 6,
                                 base: 0.5, 
                                 multi: 1.3,
                                 base_cd: 2,
                              
                   }};
                
var player_list = [{id:0,
                    name:"惠惠",
                    icon: { normal: "(∩ ◕_▩ )∩",
                            atk: "(∩ ◕_▩ )⊃━☆ Explosion",
                            damaged: ".｡･ﾟﾟ･(＞_＜)･ﾟﾟ･｡.",
                            dead: "(✖╭╮✖)",
                    },
                    skills : {"Fireball": {"lv": 1, "cd": 0},
                              "Explosion": {"lv": 0, "cd": 0},
                    },
                    str:10, 
                    dex:10,
                    inte:20,
                    gold: 20,
                    exp: 0,
                  },
                  {id:1,
                    name:"DAB",
                    icon: { normal: "＼d(－A－)b＼",
                            atk: "／d(－A－)b／┻━┻",
                            damaged: ".｡･ﾟﾟ･d(＞A＜)b･ﾟﾟ･｡.",
                            dead: "／d(＋A＋)b＼",
                    },
                    skills : {"Alacrity": {"lv": 1, "cd": 0},
                              "Deadly_shot": {"lv": 1, "cd": 0},
                    },
                    str:12, 
                    dex:20,
                    inte:1200,
                    gold: 30,
                    exp: 10000,
                  }]
                            
var monster_name_list = ["Tanglething", "Corpsefreak", "Abysssoul", "Fetidmonster", "The Ancient Mutt"]
var monster_icon_list = [ 
                      { id: 0,
                        icon: { normal: "Ψ(●｀▽´● )Ψ",
                                atk: "(~~~~~[]=¤Ψ(●｀▽´● )Ψ",
                                damaged: "ヽ ( ꒪д꒪ )ﾉ",
                                dead: "(+_+)",
                        }
                      },
                      { id: 1,
                        icon: { normal: "(▀̿̿Ĺ̯̿̿▀̿ ̿)",
                                atk: "╾━╤デ╦︻(▀̿̿Ĺ̯̿̿▀̿ ̿)",
                                damaged: "〣( ºΔº )〣",
                                dead: "(✖╭╮✖)",
                        }
                      },
                      { id: 2,
                        icon: { normal: "(˵☯‿☯˵ )",
                                atk: "╾━╤デ╦︻\_(˵☯‿☯˵)",
                                damaged: "(／。＼)",
                                dead: "（ｘ＿ｘ ）",
                        }
                      },
                    ]